spin_version = "1"
authors = ["Chai Phonbopit <phonbopit@gmail.com>"]
description = "Hello spin with HTTP Rust"
name = "hello-spin"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "hello-spin"
source = "target/wasm32-wasi/release/hello_spin.wasm"
[component.trigger]
route = "/hello"
[component.build]
command = "cargo build --target wasm32-wasi --release"
